Window.SetBackgroundTopColor(0.0, 0.01, 0.06);
Window.SetBackgroundBottomColor(0.0, 0.04, 0.14);

logo_original = Image("logo.png");

logo_altura = Window.GetHeight() * 0.24;
logo_largura = logo_altura * logo_original.GetWidth() / logo_original.GetHeight();

logo = logo_original.Scale(logo_largura, logo_altura);

logo_sprite = Sprite(logo);
logo_sprite.SetX(Window.GetWidth() / 2 - logo.GetWidth() / 2);
logo_sprite.SetY(Window.GetHeight() / 2 - logo.GetHeight() / 2);
