#!/bin/sh

set -eu

lb config noauto \
    --mode debian \
    --distribution trixie \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --archive-areas "main contrib non-free-firmware" \
    --apt-recommends false \
    --debian-installer none \
    --bootappend-live "boot=live components locales=pt_BR.UTF-8 keyboard-model=abnt2 keyboard-layouts=br timezone=America/Sao_Paulo" \
    --image-name "perspicio-os" \
    "${@}"
